name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-benchmark:
    runs-on: node20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.9'

      - name: Run tests, benchmarks, and generate coverage report
        run: |
          cd news-fetcher
          go test -coverprofile=coverage.out ./...
          go test -bench . -benchmem ./...
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: news-fetcher/coverage.html
