name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: "Run golangci-list"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --verbose
  staticcheck:
    needs: lint
    name: "Run Staticcheck"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
  gosec:
    needs: staticcheck
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
  unit-tests:
    needs: gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.9'
      - name: Run tests, benchmarks, vet, and coverage report
        run: |
          go test -coverprofile=coverage.out ./... && \
          go test -bench . -benchmem ./... -cover && \
          go tool cover -html=coverage.out -o coverage.html
          go vet ./...
