name: Go Tests + Benchmark + Vet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.9'

      - name: Run tests, benchmarks, and generate coverage report
        run: |
          go test -coverprofile=coverage.out ./... && \
          go test -bench . -benchmem ./... -cover && \
          go tool cover -html=coverage.out -o coverage.html
          go vet ./...

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: coverage.html
