name: "Staticcheck"
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  staticcheck:
    name: "Run Staticcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"